name: Jira

on:
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  call-workflow-jira:
    uses: ./.github/workflows/reusable-jira-workflow.yml
    with:
      branch_name: ${{ github.head_ref }}
    secrets: inherit
