name: Renovate

on:
  # Temporarily enable manual workflow trigger for testing
  workflow_dispatch: {}
  schedule:
    - cron: "5 2 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Renovate
        shell: bash
        run: npx renovate
        env:
          RENOVATE_CONFIG_FILE: "renovate.json"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: "debug"
