name: Terraform tools on Branch Push
on: workflow_call
jobs:
  terraform-doc-fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        run: terraform fmt -recursive
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
      - name: Check for unstaged changes
        id: git-check
        run: |
          find . -type f \( -name '*.md' -o -name '*.tf' -o -name '*.tfvars' \) -exec git add {} +
          git diff --staged --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
      - name: Commit and Push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: format terraform code and update docs"
          git push
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - uses: terraform-linters/tflint-load-config-action@v2
        with:
          source-repo: gsoft-inc/wl-reusable-workflows
          source-path: /tflint/.tflint.hcl
          source-ref: main
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run TFLint
        run: tflint -f compact
