name: Create Git Tag

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      buildVersion:
        description: 'Build version to use for the tag'
        required: true
        type: string

jobs:
  create_tag:
    runs-on: ubuntu-latest

    env:
      GIT_USER_NAME: "Infra Workleap"
      GIT_USER_EMAIL: "infra@workleap.com"
      SOURCE_VERSION_MESSAGE: "Automated tag creation"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Git Tag
        run: |
          echo "Creating tag [${buildVersion}] with message: ${{ env.SOURCE_VERSION_MESSAGE }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git tag -a ${buildVersion} -m "${{ env.SOURCE_VERSION_MESSAGE }}"
          git push origin --tags
